### ISSUE TITLE
Consider implementing an extension for paginated responses

### ISSUE THREAD

**Issue by sunecko** [BrosSquad/FastEndpoints.Template#5]
It would be a good idea to add an extension for paged responses, for example in your request you implement pagedRequest and the response pagedResponse. So that in the request you can define page size and page number
```c#
public class PagedResponse<T> : Response<IEnumerable<T>>
{
    public virtual int PageNumber { get; set; }
    public int PageSize { get; set; }
    public int TotalPages { get; set; }
    public int TotalRecords { get; set; }
}
```
Tell me if you like it and I can help with that, or do you think it is not necessary for the tamplate

**Comment by CerealKiller97** [comment]
@hectorrhg  Sounds good, go ahead added. 👍🏻

**Comment by sunecko** [comment]
@CerealKiller97  see [#6 ]
